apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

images:
- name: frontend
  newName: sidneckel/frontend
  newTag: 7c49454c614140c3bf99526aff14cf58a3d12121
- name: sidneckel/frontend
  newTag: latest
