apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

images:
- name: frontend
  newName: sidneckel/frontend
  newTag: 19b80e8958a5a4810d787af8393d4fc48238ce9a
- name: sidneckel/frontend
  newTag: latest
