apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

images:
- name: frontend
  newName: sidneckel/frontend
  newTag: 6850166e7064d3317f936c5b5469ebcb9d20aad1
- name: sidneckel/frontend
  newTag: latest
