apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

images:
- name: frontend
  newName: sidneckel/frontend
  newTag: 1efe7325a330f245dff9bbc84468e45e1d5fa286
- name: sidneckel/frontend
  newTag: latest
