apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

images:
- name: frontend
  newName: sidneckel/frontend
  newTag: 6fb981ad159e97e0f552f7de710657807379379b
- name: sidneckel/frontend
  newTag: latest
