apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

images:
- name: frontend
  newName: sidneckel/frontend
  newTag: 10e0eeac150e9361016ec02d3e5f6bd2a88f6cc0
- name: sidneckel/frontend
  newTag: latest
