apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

images:
- name: frontend
  newName: sidneckel/frontend
  newTag: 3adc44635f47aaed05f5446f8433d8b554cb4f8f
- name: sidneckel/frontend
  newTag: latest
