apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

images:
- name: frontend
  newName: sidneckel/frontend
  newTag: f0bc569465538a6d6975b9477e67a7443c8c6064
- name: sidneckel/frontend
  newTag: latest
