apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

images:
- name: frontend
  newName: sidneckel/frontend
  newTag: 98baf12b784ff865a0c7ccb363cc9afc5e2aec32
- name: sidneckel/frontend
  newTag: latest
