apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

images:
- name: frontend
  newName: sidneckel/frontend
  newTag: a573739ed547290cedef6834147668f421ffb03f
- name: sidneckel/frontend
  newTag: latest
