apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: todo-app
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 4444       # porta exposta no cluster
      targetPort: 80   # porta que o container está ouvindo (conforme netstat)
      nodePort: 30002  # porta que será exposta no node
