apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: todo-app
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 4444        # Porta do serviço (pode ser qualquer uma externa)
      targetPort: 4444    # Porta interna do container
      nodePort: 30002   # Porta acessível na sua VM
