apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: todo-app
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 4444         # Porta exposta dentro do cluster
      targetPort: 80     # Porta que o container está ouvindo (frontend containerPort: 80)
      nodePort: 30002    # Porta exposta no nó (host)
